### ISSUE TITLE
knowledge_config

### ISSUE THREAD

**Issue by jli113** [RenqiChen/Social_Science#11]
What are supposed to be in /home/bingxing2/ailab/group/ai4agr/crq/SciSci/books of Line 13 in sci_platform/configs/knowledge_config.json?

**Comment by RenqiChen** [comment]
Hello, in Google Drive, we provide a `books.tar` in `Authors` folder, which is related to ` /home/bingxing2/ailab/group/ai4agr/crq/SciSci/books`.

**Comment by jli113** [comment]
After downloading the files from Google Drive, all files need to be placed into /YOUR_Folder/SciSci, like:
/YOUR_Folder/s4s/Authors --> /YOUR_Folder/SciSci/books
/YOUR_Folder/s4s/Embeddings --> /YOUR_Folder/SciSci/faiss_index.index, /YOUR_Folder/SciSci/faiss_index_future.index
/YOUR_Folder/s4s/Papers --> /YOUR_Folder/SciSci/papers, /YOUR_Folder/SciSci/papers_future
/YOUR_Folder/s4s/adjacency.txt --> /YOUR_Folder/SciSci/adjacency.txt 
/YOUR_Folder/s4s/topic_similar.txt --> /YOUR_Folder/SciSci/topic_similar.txt

**Comment by RenqiChen** [comment]
Thanks for your kindly advice, we will add this to our readme.

**Comment by JUNO523** [comment]
同学您好，想麻烦问下您是怎么安装的呀，是用服务器进行安装的嘛，是用的什么型号的呀

**Comment by JUNO523** [comment]
用阿里云服务器装的



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 18, 2025 15:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RenqiChen/Social_Science] knowledge_config (Issue #11)


    
同学您好，想麻烦问下您是怎么安装的呀，是用服务器进行安装的嘛，是用的什么型号的呀
  
组装的台式机，按照readme安装的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  jli113 left a comment (RenqiChen/Social_Science#11)
  
同学您好，想麻烦问下您是怎么安装的呀，是用服务器进行安装的嘛，是用的什么型号的呀
  
组装的台式机，按照readme安装的
